#' Coefficient matrices of endogenous variables
#'
#' An extension of vars::Acoef() to the class "varshrinkest".
#' Returns the estimated coefficient matrices of the lagged endogenous
#' variables of a VAR(p) model.
#'
#' Consider VAR(p) model: y_t = A_1 y_{t-1} + ... + A_p y_{t-p} + C d_t + e_t.
#' The function returns the K-by-K matrices {A_1, ..., A_p} as a list object.
#'
#' @param x An object of class "varshrinkeset", generated by VARshrink().
#' @return A list object with K-by-K VAR coefficient matrices A_1, A_2, ..., A_p
#' @export
Acoef_sh <- function (x) {

  if (inherits(x, "varest")) {
    class(x) <- "varest"
  } else {
    stop("\nPlease provide an object inheriting class 'varest'.\n")
  }
  As <- vars::Acoef(x)
  return(As)
}
