#' Coefficient matrix
#'
#' An extension of vars::Bcoef() to the class "varshrinkest".
#' Returns the estimated coefficients of a VAR(p) model as a matrix.
#'
#' Consider VAR(p) model: y_t = A_1 y_{t-1} + ... + A_p y_{t-p} + C d_t + e_t.
#' The function returns the concatenated matrix (A_1, ..., A_p, C) as a matrix
#' object.
#'
#' @param x An object of class "varshrinkest" generated by VARshrink().
#' @return A matrix holding the estimated coefficients of a VAR.
#' @export
Bcoef_sh <- function (x) {

  if (inherits(x, "varest")) {
    class(x) <- "varest"
  } else {
    stop("\nPlease provide an object inheriting class 'varest'.\n")
  }
  B <- vars::Bcoef(x)
  return(B)
}
