#' A variant of vars::Bcoef() for an object of class 'varshrinkest'
#'
#' Code is modified to avoid call to data matrices ($y, $datamat)
#' and to use effective numbers of parameters of shrinkage estimates.

Bcoef.varshrinkest <- function (x)
{
  if (!inherits(x, 'varest')) {
    stop("\nPlease provide an object inheriting class 'varest'.\n")
  }
  # if (!(class(x) == "varest")) {
  #   stop("\nPlease provide an object of class 'varest', generated by 'var()'.\n")
  # }
  y.names <- names(x$varresult)  # y.names <- colnames(x$datamat[, c(1:x$K)])
  x.names <- if (x$K > 0) {
    names(coef(x$varresult[[1]]))
  } else {
    character(0)
  }
  #Z <- x$datamat[, -c(1:x$K)]
  B <- matrix(0, nrow = x$K, ncol = length(x.names))  #B <- matrix(0, nrow = x$K, ncol = ncol(Z))
  if (is.null(x$restriction)) {
    for (i in 1:x$K) {
      B[i, ] <- coef(x$varresult[[i]])
    }
  }
  else if (!(is.null(x$restriction))) {
    for (i in 1:x$K) {
      restrictions <- x$restrictions
      restrictions[i, restrictions[i, ] == TRUE] <- coef(x$varresult[[i]])
      temp <- restrictions[i, ]
      B[i, ] <- temp
    }
  }
  colnames(B) <- x.names
  rownames(B) <- y.names
  return(B)
}
