#' Forecast Error Variance Decomposition
#'
#' Computes the forecast error variance decomposition of a VAR(p) for
#' \code{n.ahead} steps.
#'
#' This function runs \code{vars::fevd()} for an object of class "varshrinkest".
#'
#' @param x Object of class "varshrinkest",
#' generated by \code{VARshrink()}.
#' @param n.ahead Integer specifying the steps.
#' @param ... Currently not used.
#' @returns An object of class "varfevd" computed by \code{vars::fevd()}.
#' @seealso \code{\link[vars]{fevd}}
#' @export
fevd.varshrinkest <- function(x, n.ahead = 10, ...) {
  if (!inherits(x, "varest")) {
    stop("\nPlease provide an object inheriting class 'varest'.\n")
  }
  if(!identical(class(x), "varest")) {
    class(x) <- "varest"
  }
  result <- vars::fevd(x, n.ahead = n.ahead, ...)
  return(result)
}
