#' Impulse response function
#'
#' Computes the impulse response coefficients of a VAR(p)
#' (or transformed VECM to VAR(p)) for n.ahead steps.
#'
#' Confidence intervals are computed by bootstrap methods in \code{vars::irf()}
#' or by Bayesian posterior distributions for an object of class
#' "varshrinkest".
#'
#' @param x Object of class "varshrinkest",
#' generated by \code{VARshrink()}
#' @param impulse A character vector of the impulses,
#' default is all variables.
#' @param response A character vector of the responses,
#' default is all variables.
#' @param n.ahead Integer specifying the steps.
#' @param ortho Logical, if TRUE (the default) the
#' orthogonalised impulse response coefficients are
#' computed (only for objects of class 'varshrinkest').
#' @param cumulative Logical, if TRUE the cumulated impulse
#' response coefficients are computed. The default value
#' is false.
#' @param boot Logical, if TRUE (the default) bootstrapped
#' confidence bands or Bayesian credible bands for the impulse
#' response coefficients are computed.
#' @param ci Numeric, the confidence level for the
#' bootstrapped confidence or Bayesian credible bands.
#' @param runs An integer, specifying the runs for the
#' bootstrap.
#' @param seed An integer, specifying the seed for the
#' rng of the bootstrap.
#' @param ... Currently not used.
#' @returns An object of class "varirf" with the same component structure as
#' \code{vars::irf()}.
#' @details For objects without stored MCMC draws, this method delegates to
#' \code{vars::irf()}. For objects with \code{mcmc.param}, point estimates are
#' computed from the fitted VAR coefficients and credible bands are computed
#' from posterior MCMC draws.
#' @seealso \code{\link[vars]{irf}}
#' @export
irf.varshrinkest <-
  function(x, impulse = NULL, response = NULL, n.ahead = 10, ortho = TRUE,
           cumulative = FALSE, boot = TRUE, ci = 0.95, runs = 100, seed = NULL,
           ...) {
    if (!inherits(x, "varest")) {
      stop("\nPlease provide an object inheriting class 'varest'.\n")
    }

    # If the object does not have MCMC parameters, use the method for "varest"
    if (is.null(x$mcmc.param)) {
      if (!identical(class(x), "varest")) {
        class(x) <- "varest"
      }
      result <- vars::irf(x, impulse = impulse, response = response,
                          n.ahead = n.ahead, ortho = ortho,
                          cumulative = cumulative, boot = boot, ci = ci,
                          runs = runs, seed = seed, ...)
    } else {
      result <- irf_bayes(x, impulse = impulse, response = response,
                          n.ahead = n.ahead, ortho = ortho,
                          cumulative = cumulative, boot = boot, ci = ci,
                          ...)
    }
    return(result)
  }

# Compute a vars-compatible "varirf" object from stored posterior draws.
irf_bayes <-
  function(x, impulse = NULL, response = NULL, n.ahead = 10, ortho = TRUE,
           cumulative = FALSE, boot = TRUE, ci = 0.95, ...) {
    # Match vars::irf.varest() ordering and validation of variable names.
    y.names <- colnames(x$y)
    if (is.null(impulse)) {
      impulse <- y.names
    } else {
      impulse <- as.vector(as.character(impulse))
      if (any(!(impulse %in% y.names))) {
        stop(paste0("\nPlease provide variables names in impulse\nthat are ",
                    "in the set of endogenous variables.\n"))
      }
      impulse <- subset(y.names, subset = y.names %in% impulse)
    }
    if (is.null(response)) {
      response <- y.names
    } else {
      response <- as.vector(as.character(response))
      if (any(!(response %in% y.names))) {
        stop(paste0("\nPlease provide variables names in response\nthat are ",
                    "in the set of endogenous variables.\n"))
      }
      response <- subset(y.names, subset = y.names %in% response)
    }

    n.ahead <- abs(as.integer(n.ahead))

    # The central IRF is based on the fitted posterior mean coefficients.
    point.param <- list(Psi = t(Bcoef_sh(x)), Sigma = get_irf_sigma(x))
    point.irf <- irf_array_from_param(point.param, K = x$K, p = x$p,
                                      n.ahead = n.ahead, ortho = ortho)
    irs <- irf_list_from_array(point.irf, impulse = impulse,
                               response = response, y.names = y.names,
                               n.ahead = n.ahead, cumulative = cumulative)

    Lower <- NULL
    Upper <- NULL
    mcmccycle <- length(x$mcmc.param)
    if (mcmccycle == 0) {
      stop("\nBayesian IRFs require at least one MCMC parameter draw.\n")
    }
    if (boot) {
      ci <- as.numeric(ci)
      if ((ci <= 0) || (ci >= 1)) {
        stop(paste0("\nPlease provide a number between 0 and 1 for the ",
                    "confidence interval.\n"))
      }
      alpha <- 1 - ci
      probs <- c(alpha / 2, 1 - alpha / 2)

      # Bayesian bands use posterior quantiles of the draw-level IRFs.
      draws <- lapply(x$mcmc.param, irf_array_from_param, K = x$K, p = x$p,
                      n.ahead = n.ahead, ortho = ortho)
      posterior <- lapply(draws, irf_list_from_array, impulse = impulse,
                          response = response, y.names = y.names,
                          n.ahead = n.ahead, cumulative = cumulative)
      bands <- irf_posterior_bands(posterior, impulse = impulse,
                                   response = response, probs = probs)
      Lower <- bands$Lower
      Upper <- bands$Upper

      # Keep the vars::irf.varest() convention: ci stores alpha when boot=TRUE.
      ci <- alpha
    }

    result <- list(irf = irs, Lower = Lower, Upper = Upper,
                   response = response, impulse = impulse, ortho = ortho,
                   cumulative = cumulative, runs = mcmccycle, ci = ci,
                   boot = boot, model = "varest")
    class(result) <- "varirf"
    return(result)
  }

# Convert one coefficient/covariance draw into Phi or orthogonalized Psi arrays.
irf_array_from_param <- function(param, K, p, n.ahead, ortho) {
  if (is.null(param$Psi)) {
    stop("VARshrink parameter draws must contain a 'Psi' component.\n")
  }
  Psi <- as.matrix(param$Psi)
  if (nrow(Psi) < K * p || ncol(Psi) != K) {
    stop("VARshrink parameter 'Psi' has incompatible dimensions.\n")
  }

  B <- t(Psi[seq_len(K * p), , drop = FALSE])

  # Recursively build the MA coefficient matrices Phi_0, ..., Phi_n.
  Phi <- array(0, dim = c(K, K, n.ahead + 1))
  Phi[, , 1] <- diag(K)
  if (n.ahead >= 1) {
    for (h in seq_len(n.ahead)) {
      tmp <- matrix(0, nrow = K, ncol = K)
      for (lag in seq_len(min(h, p))) {
        A <- matrix(B[, ((lag - 1) * K + 1):(lag * K), drop = FALSE],
                    nrow = K, ncol = K)
        tmp <- tmp + Phi[, , h - lag + 1] %*% A
      }
      Phi[, , h + 1] <- tmp
    }
  }
  if (!ortho) {
    return(Phi)
  }
  if (is.null(param$Sigma)) {
    stop("\nOrthogonalized Bayesian IRFs require a 'Sigma' component.\n")
  }

  # Orthogonalization follows vars::Psi.varest(): Psi_h = Phi_h %*% chol(Sigma).
  P <- t(chol(param$Sigma))
  Psi.ortho <- array(0, dim = dim(Phi))
  for (i in seq_len(dim(Phi)[3])) {
    Psi.ortho[, , i] <- Phi[, , i] %*% P
  }
  return(Psi.ortho)
}

# Reformat a K x K x horizon IRF array into vars::irf()'s list-of-matrices form.
irf_list_from_array <- function(irf, impulse, response, y.names, n.ahead,
                                cumulative) {
  dimnames(irf) <- list(y.names, y.names, NULL)
  irs <- vector("list", length(impulse))
  names(irs) <- impulse
  for (i in seq_along(impulse)) {
    values <- irf[response, impulse[i], seq_len(n.ahead + 1), drop = FALSE]
    irs[[i]] <- matrix(aperm(values, c(3, 1, 2)), nrow = n.ahead + 1,
                       ncol = length(response))
    colnames(irs[[i]]) <- response
    if (cumulative) {
      irs[[i]] <- apply(irs[[i]], 2, cumsum)
      if (length(response) == 1) {
        irs[[i]] <- matrix(irs[[i]], ncol = 1)
        colnames(irs[[i]]) <- response
      }
    }
  }
  return(irs)
}

# Compute lower and upper posterior quantile bands for each
# impulse-response pair.
irf_posterior_bands <- function(posterior, impulse, response, probs) {
  Lower <- vector("list", length(impulse))
  Upper <- vector("list", length(impulse))
  names(Lower) <- impulse
  names(Upper) <- impulse

  for (i in seq_along(impulse)) {
    n.ahead <- nrow(posterior[[1]][[i]])
    mat.l <- matrix(NA, nrow = n.ahead, ncol = length(response))
    mat.u <- matrix(NA, nrow = n.ahead, ncol = length(response))
    colnames(mat.l) <- response
    colnames(mat.u) <- response
    for (j in seq_along(response)) {
      for (h in seq_len(n.ahead)) {
        values <- vapply(posterior, function(draw) draw[[i]][h, j],
                         numeric(1))
        mat.l[h, j] <- stats::quantile(values, probs[1], na.rm = TRUE)
        mat.u[h, j] <- stats::quantile(values, probs[2], na.rm = TRUE)
      }
    }
    Lower[[i]] <- mat.l
    Upper[[i]] <- mat.u
  }
  return(list(Lower = Lower, Upper = Upper))
}

# Prefer the Bayesian Sigma estimate; otherwise fall back to
# residual covariance.
get_irf_sigma <- function(x) {
  if (!is.null(x$Sigma)) {
    return(x$Sigma)
  }
  dfr <- df.residual(x$varresult[[1]])
  return(crossprod(resid(x)) / dfr)
}
