#' Coefficient matrices of the orthogonalized MA representation
#'
#' Returns the estimated orthogonalized coefficient matrices of the moving
#' average representation of a stable VAR(p).
#'
#' This is an extension of \code{vars::Psi.varest()} for the class
#' "varshrinkest".
#'
#' @param x An object of class "varshrinkest",
#' generated by \code{VARshrink()}.
#' @param nstep An integer specifying the number of orthogonalized moving
#' error coefficient matrices to be calculated.
#' @param ... Currently not used.
#' @returns An array with dimension \eqn{K \times K \times (nstep + 1)} holding
#' the estimated coefficients of the orthogonalized moving average
#' representation.
#' @seealso \code{\link[vars]{Psi}}
#' @importFrom stats df.residual resid
#' @export
Psi.varshrinkest <- function(x, nstep = 10, ...) {
  if (!(inherits(x, "varest"))) {
    stop("\nPlease provide an object inheriting class 'varest'.\n")
  }
  nstep <- abs(as.integer(nstep))
  Phi <- Phi(x, nstep = nstep)
  Psi <- array(0, dim = dim(Phi))
  dfr <- df.residual(x$varresult[[1]])
  sigma.u <- crossprod(resid(x)) / dfr
  P <- t(chol(sigma.u))
  dim3 <- dim(Phi)[3]
  for (i in 1:dim3) {
    Psi[, , i] <- Phi[, , i] %*% P
  }
  return(Psi)
}
